# Generated by Django 4.1.6 on 2023-03-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
        migrations.AlterModelTable(
            name='contacts',
            table='contacts',
        ),
    ]
