# Generated by Django 4.1.6 on 2023-03-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_contact_contacts_alter_contacts_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
