# Generated by Django 4.1.6 on 2023-03-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_contact_table_alter_dform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='dform',
            table='donate',
        ),
    ]
